"""add logo_url to universities

Revision ID: 3d7e430f3766
Revises: e14e26d8a8c3
Create Date: 2026-07-23 14:13:45.278313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7e430f3766'
down_revision: Union[str, Sequence[str], None] = 'e14e26d8a8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', 
                   sa.Column('logo_url', 
                   sa.String(length=500), 
                   nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'logo_url')
    # ### end Alembic commands ###
