"""add newsletter subscribers

Revision ID: 99d676259f8c
Revises: 88d50ea9303d
Create Date: 2026-07-07 23:03:49.424181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d676259f8c'
down_revision: Union[str, Sequence[str], None] = '88d50ea9303d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_admission_details_university_id'), 'admission_details', ['university_id'], unique=False)
    op.create_index(op.f('ix_courses_university_id'), 'courses', ['university_id'], unique=False)
    op.create_index(op.f('ix_ranking_scores_university_id'), 'ranking_scores', ['university_id'], unique=False)
    op.create_index(op.f('ix_ranking_scores_year'), 'ranking_scores', ['year'], unique=False)
    op.create_index(op.f('ix_saved_universities_university_id'), 'saved_universities', ['university_id'], unique=False)
    op.create_index(op.f('ix_saved_universities_user_id'), 'saved_universities', ['user_id'], unique=False)
    op.create_index(op.f('ix_universities_country'), 'universities', ['country'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.drop_constraint(op.f('university_metrics_university_id_key'), 'university_metrics', type_='unique')
    op.create_index(op.f('ix_university_metrics_university_id'), 'university_metrics', ['university_id'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_university_metrics_university_id'), table_name='university_metrics')
    op.create_unique_constraint(op.f('university_metrics_university_id_key'), 'university_metrics', ['university_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_country'), table_name='universities')
    op.drop_index(op.f('ix_saved_universities_user_id'), table_name='saved_universities')
    op.drop_index(op.f('ix_saved_universities_university_id'), table_name='saved_universities')
    op.drop_index(op.f('ix_ranking_scores_year'), table_name='ranking_scores')
    op.drop_index(op.f('ix_ranking_scores_university_id'), table_name='ranking_scores')
    op.drop_index(op.f('ix_courses_university_id'), table_name='courses')
    op.drop_index(op.f('ix_admission_details_university_id'), table_name='admission_details')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    # ### end Alembic commands ###
